### PR TITLE
Change Status to Thai / Add filter delay

### PR DESCRIPTION
**Pull request by Mark169Z**
Change all Status to Thai

Add delay to filter to avoid error (when filter too fast, it could not find any data)
- if you know the better solution, you can tell me

### CODE REVIEW

**Comment by Chatchaponz** [comment]
About the bug, can you provide some pictures for me???

**Comment by Mark169Z** [comment]
> About the bug, can you provide some pictures for me???
Oh, I think I figure out why this bug happened. I am fixing it

**Comment by Chatchaponz** [comment]
I still don't think setTimeOut is a good solution here lol. 
Please provide me more information about the bug (with picture will be great cuz I didn't run this code myself ;-;)
And I do really want to know what do you think is the problem or cause of this bug and why you think current solution is OK krub :)

**Comment by Chatchaponz** [comment]
It would be great if u can explain to me in discord

**Comment by Mark169Z** [comment]
P Ryu krub, I think the useState method is a good method krub, considering the conversation we had about the scroll bug. However, since the clear part runs afterward, it will still trigger the fetching part one more time due to the state change.

**Comment by Mark169Z** [comment]
Finished krub

**Review by Chatchaponz — APPROVED** [review]

**Review by NANAYEMYINTKYI — APPROVED** [review]

**Pull request merged**
